basic_weight_decay: 0
clean_count: -1
cls_emb_dim: 8
cnn_drop_out: 0.3
cpus_per_trail: 1
epochs: 15
eval_batch_size: 32
gw_dropout: 0.2
gw_hidden_dim: 32
hidden_size: 64
is_debug: false
is_deeper_weight: false
is_guoqing_method: false
kernel_num: 100
kernel_sizes: 3,4,5
max_length: 50
meta_weight_decay: 0
model_name: baseline
pre_train_basic_epochs: 0
pre_train_meta_epochs: 0
train_batch_size: 32
is_freeze: false
class_num: 4
is_overwrite_file: false
is_agg_weak: false
is_only_clean: true
weak_ratio: 0.8
is_concat_weak_clean: false
# placeholder
n_high_cov: 3
grid_search:
  basic_lr_rate: [0.00001, 0.00005, 0.00003, 0.000005]
  # 1 - weak_ratio data for sampling
  clean_ratio: [-100]
  random_seed: [123, 456, 789, 10, 49]
